### ISSUE TITLE
AJAX HTTP error on install

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#9]
Getting the following error upon install - https://skitch.com/gusaus/etdjc/installing-drupal-drupal

**Comment by discipolo** [comment]
this is caused by SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'module' cannot be null

which usually occurs when a feature sets a permission for which the dependency is not yet enabled

i suspected a correlation with menu block module http://drupal.org/node/1425342 or our install file setting permissions wrong  

btw. we can actually omit the entire install file if we decide where to define users, input formats and permissions instead.
something along the lines of https://drupal.org/project/apps_compatible or http://drupal.org/sandbox/hefox/1601154

but it turns out the permissions in question are actuially in panopoly_core.install

user_role_grant_permissions(DRUPAL_ANONYMOUS_RID, array('search content'));
user_role_grant_permissions(DRUPAL_AUTHENTICATED_RID, array('search content'))

this is the issue:
http://drupal.org/node/737816

search is enabled though...

**Comment by discipolo** [comment]
created patch and included it http://drupal.org/node/1780020

**Comment by discipolo** [comment]
http://drupal.org/node/1780020

**Comment by gusaus** [comment]
Happening again on the latest release - 
![installing drupal drupal 2013-05-15 12-23-31](https://f.cloud.github.com/assets/113996/508912/f2f3687a-bd94-11e2-9869-579636c145c1.jpg)

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://dev-pushtape-panels.gotpantheon.com/install.php?profile=pushtape&locale=en&id=1&op=do StatusText: OK ResponseText: Home | Drupal Home Installation tasksChoose profile(done)Choose language(done)Verify requirements(done)Set up database(done)Install profile(active)Configure siteChoose a themeFinished Warning message The image resize filter has been installed. Before this does anything, the image resize filter needs to be added to one or more text formats. Visit the text format administration to set up this filter. Status message To use menu blocks, find the "Add menu block" link on the administer blocks page. SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'module' cannot be null 

![home drupal 2013-05-15 12-27-36](https://f.cloud.github.com/assets/113996/508926/83770ef6-bd95-11e2-9446-0e231c8154b4.jpg)

**Comment by gusaus** [comment]
An update to pushtape_discography and removing pushtape_admin as a dependency resolved this issue. Still need to clean up the permissions and input formats, but can open a new issue for that....
